### ISSUE TITLE
Api token

### ISSUE THREAD

**Issue by GGenetta** [blockchain/lib-exchange-client#11]
Hi, 

On the exchange I created my API token. When i try on the example page (https://api.blockchain.com/v3/#/) it will not load the /Fees tag because of a internal error (500). 
When I try this with the python script it is giving me the same error code. 
If I try a other tag, for example the /accounts tag, I receive the error 401 unauthorized  error. 
Same with the python script. 

Is everything working as supposed to or am I doing something wrong? 
Thank you, 
GG

**Comment by Heanware** [comment]
how did you solve this?

**Comment by FounderCasey** [comment]
@GGenetta did you solve this?

cc @Heanware

**Comment by Heanware** [comment]
@FounderCasey No
